spring:
  application:
    name: lemondrop
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/lemondrop
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080
  error:
    path: /error
    include-message: always

app:
  whatsapp:
    country-code: "57" # Default country code (e.g. Colombia)
  order:
    prefix: "LD"
